services:
  postgres:
    container_name: postgres
    build: ./infra/db/postgres
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - internal

  core_service:
    build:
      context: ./backend/core_service
      dockerfile: Dockerfile
      args:
        SMTP_SECRET_CODE: ${SMTP_SECRET_CODE}
        EMAIL_SENDER: ${EMAIL_SENDER}
    container_name: core_service
    volumes:
      - core_data:/app/saved
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      core_service:
        condition: service_healthy

    networks:
      - external
      - internal

volumes:
  pg_data:
  core_data:

networks:
  internal:
    driver: bridge

  external:
    driver: bridge
