services:
  postgres:
    container_name: postgres
    build: ./infra/db/postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - internal

  core_service:
    build: ./backend/core_service
    container_name: core_service
    volumes:
      - core_data:/app/saved
    depends_on:
      - postgres
    networks:
      - internal

  ai_service:
    build: ./backend/ai_service
    container_name: ai_service
    networks:
      - internal

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80
    networks:
      - external
      - internal

volumes:
  pg_data:
  core_data:

networks:
  internal:
    driver: bridge

  external:
    driver: bridge
