--
-- PostgreSQL database dump
--

\restrict m8MCdRJd9f9NltmmTRaq7atEL82Hd4AZqyQxxbczOD86XckP26OFQHUBu8lc5QW

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: galery_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.galery_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.galery_status OWNER TO postgres;

--
-- Name: story_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.story_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.story_status OWNER TO postgres;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'user'
);


ALTER TYPE public.user_role OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: available_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.available_tags (
    id integer NOT NULL,
    name character varying(64)
);


ALTER TABLE public.available_tags OWNER TO postgres;

--
-- Name: available_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.available_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.available_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    name character varying(64),
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    date timestamp with time zone NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_images (
    event_id integer,
    path character varying(255)
);


ALTER TABLE public.events_images OWNER TO postgres;

--
-- Name: galery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery (
    publishing_id character varying(255) NOT NULL,
    author_id uuid,
    status public.galery_status NOT NULL
);


ALTER TABLE public.galery OWNER TO postgres;

--
-- Name: galery_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery_photos (
    path character varying(255) NOT NULL,
    publishing_id character varying(255)
);


ALTER TABLE public.galery_photos OWNER TO postgres;

--
-- Name: partners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.partners OWNER TO postgres;

--
-- Name: partners_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_photos (
    path character varying(255) NOT NULL,
    partner_id uuid
);


ALTER TABLE public.partners_photos OWNER TO postgres;

--
-- Name: stories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories (
    id integer NOT NULL,
    author_id uuid,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    status public.story_status NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    updated_by uuid
);


ALTER TABLE public.stories OWNER TO postgres;

--
-- Name: stories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_images (
    story_id integer,
    path character varying(255)
);


ALTER TABLE public.stories_images OWNER TO postgres;

--
-- Name: stories_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_tags (
    story_id integer,
    tag_id integer
);


ALTER TABLE public.stories_tags OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255),
    password character varying(255) NOT NULL,
    name character varying(32) NOT NULL,
    surname character varying(32) NOT NULL,
    avatar character varying(255),
    role public.user_role NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: available_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.available_tags (id, name) FROM stdin;
1	История пруда
2	Экология
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (id, name, description, created_at, updated_at, created_by, date) FROM stdin;
1	Птичий перезвон на Соловьином	Эко-фестиваль в честь возвращения птиц на обновленный водоем. В программе: мастер-класс от орнитологов по распознаванию птичьих голосов, развешивание правильных кормушек, лекция о бережном отношении к уткам и запуск первой партии рыбы в очищенный пруд.	2026-07-06 12:02:37.025138+00	2026-07-06 12:02:37.025138+00	034e5f97-61e9-481b-8d0e-dc5d12935786	2026-05-16 11:00:00+00
2	Тайны старого карьера: от кирпича до оазиса	Исторический пикник-лекторий под открытым небом. Краеведы расскажут историю Новой слободы и кирпичного завода XIX века, покажут архивные фотографии пруда «Кирпичики», а активисты поделятся хрониками борьбы за спасение водоема. Завершится вечер акустическим концертом у воды.	2026-07-06 12:04:21.945747+00	2026-07-06 12:04:21.945747+00	034e5f97-61e9-481b-8d0e-dc5d12935786	2027-07-21 10:00:00+00
\.


--
-- Data for Name: events_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events_images (event_id, path) FROM stdin;
\.


--
-- Data for Name: galery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery (publishing_id, author_id, status) FROM stdin;
e5dd32e0-3117-460d-8f63-bc18f63b3aad	034e5f97-61e9-481b-8d0e-dc5d12935786	approved
b9b652fc-6f45-4d16-9795-ffad87794928	034e5f97-61e9-481b-8d0e-dc5d12935786	approved
\.


--
-- Data for Name: galery_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery_photos (path, publishing_id) FROM stdin;
7563c5ec-08bb-434f-a249-03356fa45f13.jpg	e5dd32e0-3117-460d-8f63-bc18f63b3aad
4357e9e0-fb7d-466d-baf9-9d1d4f8ccd4a.jpg	e5dd32e0-3117-460d-8f63-bc18f63b3aad
9ed79e3a-21e2-4a10-aa17-35fb77b7e09f.jpg	e5dd32e0-3117-460d-8f63-bc18f63b3aad
0db91d72-16df-496a-8f1d-9aedbc63ac0b.jpg	b9b652fc-6f45-4d16-9795-ffad87794928
0b25b1b2-5cc1-4895-a3a0-c87acb109aa1.jpg	b9b652fc-6f45-4d16-9795-ffad87794928
\.


--
-- Data for Name: partners; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners (id, name, description) FROM stdin;
64d63c2e-fc51-41ef-adf2-d8ed56079ffe	Алексей Мокеев 	Алексей Мокеев - член общественной палаты администрации Владимирской области, эксперт Народного фронта | Владимир, сопредседатель благотворительного фонда "Создадим будущее вместе". Участвовал в агитации жителей города за голосование по проекту благоустройства территории пруда, так же выступал на Владимирском телевидении!
c012d3d3-1fdf-403f-85d3-0eb72ad3513e	Молодёжный клуб РГО «Владимир» 	Владимирское областное отделение Русского географического общества — региональная структура одной из старейших научных организаций России, основанной в 1845 году. Отделение объединяет исследователей, педагогов, краеведов и общественных деятелей, которые занимаются изучением и сохранением природного, географического и культурно-исторического наследия Владимирского края. Среди ключевых направлений работы — экспедиционная и просветительская деятельность, экологическое воспитание, поддержка научного туризма и краеведения, а также участие в общественных инициативах по охране окружающей среды. Председателем Отделения является Антипин Сергей Владимирович.\nСоловьиный пруд стал одним из объектов устойчивого внимания организации: члены отделения участвовали в экологических акциях и субботниках на территории водоёма, содействовали привлечению волонтёров и широкому информированию жителей о состоянии пруда и мерах по его реабилитации. В рамках деятельности отделения формировалась экспертная позиция по вопросам сохранения городских водоёмов как элементов природного каркаса Владимира.\n\nМолодёжный клуб РГО «Владимир» создан на базе МБУ «Молодёжный центр» г. Владимира и входит в структуру Молодёжного движения Русского географического общества, объединяющего более 220 клубов по всей стране. Руководство клубом осуществляет Шишкина Светлана Александовна.\nМиссия клуба — приобщение молодёжи к миру «большой географии», изучение и сохранение природного и культурного наследия родного края. Активисты клуба реализуют исследовательские, просветительские и добровольческие проекты, участвуют в географических олимпиадах и конкурсах федерального уровня, организуют экспедиции и экскурсии по Владимирской области.\nВ работе по Соловьиному пруду Молодёжный клуб выступил важной практической силой: волонтёры клуба регулярно участвовали в субботниках и экологических акциях на территории водоёма, помогали в уборке береговой зоны, высадке растений и наведении порядка на прилегающей территории. Деятельность клуба — наглядный пример того, как молодёжь может быть не сторонним наблюдателем, а активным участником сохранения городской природы.\nСегодня Молодёжный клуб РГО «Владимир» продолжает развиваться: его активисты участвуют в чемпионатах России по географии, краеведческих конкурсах, лекциях-спектаклях о выдающихся исследователях Владимирского края, слётах молодёжного движения РГО и форумах добровольцев. Клуб открыт для всех, кто неравнодушен к географии, экологии и судьбе родного города.\n\nСотрудничество Владимирского отделения РГО и Молодёжного клуба «Владимир» с инициативой по сохранению Соловьиного пруда — пример того, как наука, гражданская активность и любовь к родному месту объединяются ради общего дела.
dc6d47e3-bf5b-41b2-8a53-aae4d527f860	БПС г.Владимир. Отряд имени Андрея Дубенского 	Владимирский отряд Братства Православных Следопытов (БПС) имени Андрея Дубенского. Православные скауты (следопыты) представляют собой братство людей, стремящихся к личностному, духовному и умственному развитию.
\.


--
-- Data for Name: partners_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_photos (path, partner_id) FROM stdin;
17f1e790-b002-4bdd-90c2-a9ebc8ad87a2.jpg	64d63c2e-fc51-41ef-adf2-d8ed56079ffe
23d685c1-b362-40e3-98b8-093991ad3ed4.jpg	64d63c2e-fc51-41ef-adf2-d8ed56079ffe
9904929f-dd50-4eb1-8f7f-026308fcc882.jpg	c012d3d3-1fdf-403f-85d3-0eb72ad3513e
8436eb34-f63f-44aa-a817-494be878b2e2.jpg	c012d3d3-1fdf-403f-85d3-0eb72ad3513e
2359190a-0967-4e4e-8312-63631e027c87.jpg	c012d3d3-1fdf-403f-85d3-0eb72ad3513e
e9df7d5e-7681-40bd-9c4a-8941e513b9ab.jpg	c012d3d3-1fdf-403f-85d3-0eb72ad3513e
98e32df1-f222-4114-966e-9b19e577cc4c.jpg	dc6d47e3-bf5b-41b2-8a53-aae4d527f860
26f892c6-0732-474e-aaea-a8f9e65310f5.jpg	dc6d47e3-bf5b-41b2-8a53-aae4d527f860
ec3beed4-f370-4c10-a829-44489a0c3a62.jpg	dc6d47e3-bf5b-41b2-8a53-aae4d527f860
6dcaf5ac-e307-4f48-a12d-de2675bdb0ec.jpg	dc6d47e3-bf5b-41b2-8a53-aae4d527f860
\.


--
-- Data for Name: stories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories (id, author_id, title, content, status, created_at, updated_at, updated_by) FROM stdin;
1	034e5f97-61e9-481b-8d0e-dc5d12935786	От глиняного карьера до романтичных трелей	История самого старого из сохранившихся городских водоемов Владимира началась в XIX веке. В те времена на пустыре за Юрьевской заставой (ныне район Новой слободы) активно работали частные кирпичные заводы Студьицкого и Ермолаева, позже объединенные в завод имени Володарского. Рождение водоема: Рабочие годами выкапывали из огромного карьера глину для производства кирпичей. Со временем производство закрылось, а глубокий котлован глубиной более 4,5 метров стал стремительно заполняться чистейшей водой из подземных природных ключей.Откуда пошли названия: Местные жители долгое время называли водоем «Кирпичики» — в память о заводе. Однако народное и самое известное название — «Соловьиный» — пруд получил благодаря густым зеленым зарослям вокруг, в которых каждую весну собирались сотни птиц, оглашая округу звонкими трелями. Водоем более полувека использовался для технического водоснабжения, но постепенно превратился в любимое место отдыха горожан.	approved	2026-07-06 11:57:03.817756+00	2026-07-06 11:57:03.817756+00	\N
2	034e5f97-61e9-481b-8d0e-dc5d12935786	Народное спасение и масштабное возрождение	Долгое время Соловьиный пруд находился в запустении, зарастал тиной и постепенно превращался в свалку бытового мусора посреди жилой застройки. Экологическая история пруда — это хроника борьбы жителей за жизнь уникальной городской экосистемы.Народные субботники: В 2014–2015 годах инициативная группа горожан и активистов ВлГУ забила тревогу. Они своими силами провели масштабные субботники, добились очистки дна от ила, убрали хлам и вернули пруду способность наполняться родниковой водой. На воду спустили плавающий домик для уток, а в воду запустили карасей и мальков. Пруд стал настоящим оазисом, однако маленькая замкнутая экосистема регулярно подвергалась угрозам: от нехватки кислорода зимой до сообщений о незаконных сливах.Новый этап (2026 год): Летом 2026 года началась масштабная экологическая регенерация водоема по программе комфортной городской среды. Пруд полностью осушили, чтобы бережно выловить рыбу, вычистить дно от многолетних донных отложений и мусора. Самым важным шагом стало решение пробурить артезианскую скважину глубиной 180 метров. Она будет постоянно питать Соловьиный пруд чистой водой, защищая его от высыхания и зацветания, что позволит полностью сохранить хрупкий биоценоз.	approved	2026-07-06 12:00:58.137211+00	2026-07-06 12:00:58.137211+00	\N
\.


--
-- Data for Name: stories_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_images (story_id, path) FROM stdin;
1	a408cf12-32e3-40b6-ba01-e958b272edf8.jpg
2	e0dedb23-9ba7-436f-bb6f-8f98ff97bb74.jpg
2	1d772620-cad5-4def-a165-48ee6253e565.jpg
\.


--
-- Data for Name: stories_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_tags (story_id, tag_id) FROM stdin;
1	1
2	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, name, surname, avatar, role) FROM stdin;
034e5f97-61e9-481b-8d0e-dc5d12935786	admin@admin.ru	8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918	Admin	Adminov	admin_avatar.png	admin
\.


--
-- Name: available_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.available_tags_id_seq', 2, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_id_seq', 2, true);


--
-- Name: stories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stories_id_seq', 2, true);


--
-- Name: available_tags available_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.available_tags
    ADD CONSTRAINT available_tags_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: galery_photos galery_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_pkey PRIMARY KEY (path);


--
-- Name: galery galery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_pkey PRIMARY KEY (publishing_id);


--
-- Name: partners_photos partners_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_pkey PRIMARY KEY (path);


--
-- Name: partners partners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_pkey PRIMARY KEY (id);


--
-- Name: stories stories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: events events_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: events_images events_images_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_images
    ADD CONSTRAINT events_images_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: galery galery_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: galery_photos galery_photos_publishing_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_publishing_id_fkey FOREIGN KEY (publishing_id) REFERENCES public.galery(publishing_id);


--
-- Name: partners_photos partners_photos_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: stories stories_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: stories_images stories_images_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_images
    ADD CONSTRAINT stories_images_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.available_tags(id);


--
-- Name: stories stories_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict m8MCdRJd9f9NltmmTRaq7atEL82Hd4AZqyQxxbczOD86XckP26OFQHUBu8lc5QW

