--
-- PostgreSQL database dump
--

\restrict GH1eW69dBG9hgFOrIjnRJRM9rREBejHKeDHWM0SOhaYO0CYEBXezvn1WabK4eaX

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: galery_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.galery_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.galery_status OWNER TO postgres;

--
-- Name: partner_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.partner_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.partner_status OWNER TO postgres;

--
-- Name: story_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.story_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.story_status OWNER TO postgres;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'user'
);


ALTER TYPE public.user_role OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: available_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.available_tags (
    id integer NOT NULL,
    name character varying(64)
);


ALTER TABLE public.available_tags OWNER TO postgres;

--
-- Name: available_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.available_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.available_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    name character varying(64),
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    date timestamp with time zone NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_images (
    event_id integer,
    path character varying(255)
);


ALTER TABLE public.events_images OWNER TO postgres;

--
-- Name: galery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery (
    publishing_id character varying(255) NOT NULL,
    author_id uuid,
    status public.galery_status NOT NULL,
    description character varying(1023)
);


ALTER TABLE public.galery OWNER TO postgres;

--
-- Name: galery_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery_photos (
    path character varying(255) NOT NULL,
    publishing_id character varying(255)
);


ALTER TABLE public.galery_photos OWNER TO postgres;

--
-- Name: partners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    trusted boolean DEFAULT false,
    status public.partner_status NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.partners OWNER TO postgres;

--
-- Name: partners_docs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_docs (
    path character varying NOT NULL,
    partner_id uuid
);


ALTER TABLE public.partners_docs OWNER TO postgres;

--
-- Name: partners_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_photos (
    path character varying(255) NOT NULL,
    partner_id uuid
);


ALTER TABLE public.partners_photos OWNER TO postgres;

--
-- Name: partners_reps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_reps (
    partner_id uuid,
    user_id uuid
);


ALTER TABLE public.partners_reps OWNER TO postgres;

--
-- Name: partners_socials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_socials (
    partner_id uuid,
    social character varying(64) NOT NULL,
    url character varying(255) NOT NULL
);


ALTER TABLE public.partners_socials OWNER TO postgres;

--
-- Name: stories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories (
    id integer NOT NULL,
    author_id uuid,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    status public.story_status NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    updated_by uuid
);


ALTER TABLE public.stories OWNER TO postgres;

--
-- Name: stories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_images (
    story_id integer,
    path character varying(255)
);


ALTER TABLE public.stories_images OWNER TO postgres;

--
-- Name: stories_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_tags (
    story_id integer,
    tag_id integer
);


ALTER TABLE public.stories_tags OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255),
    password character varying(255) NOT NULL,
    name character varying(32) NOT NULL,
    surname character varying(32) NOT NULL,
    avatar character varying(255),
    role public.user_role NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: available_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.available_tags (id, name) FROM stdin;
1	История пруда
2	Экология
3	Реставрация
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (id, name, description, created_at, updated_at, created_by, date) FROM stdin;
1	Тайны старого карьера: от кирпича до оазиса	Исторический пикник-лекторий под открытым небом. Краеведы расскажут историю Новой слободы и кирпичного завода XIX века, покажут архивные фотографии пруда «Кирпичики», а активисты поделятся хрониками борьбы за спасение водоема. Завершится вечер акустическим концертом у воды.	2026-07-26 11:03:27.601545+00	2026-07-26 11:03:27.601545+00	77d16713-5d52-40fb-8a30-1ccacda822f5	2027-07-21 12:00:00+00
2	Птичий перезвон на Соловьином	Эко-фестиваль в честь возвращения птиц на обновленный водоем. В программе: мастер-класс от орнитологов по распознаванию птичьих голосов, развешивание правильных кормушек, лекция о бережном отношении к уткам и запуск первой партии рыбы в очищенный пруд.	2026-07-26 11:05:17.692392+00	2026-07-26 11:05:17.692392+00	77d16713-5d52-40fb-8a30-1ccacda822f5	2026-05-16 11:00:00+00
\.


--
-- Data for Name: events_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events_images (event_id, path) FROM stdin;
\.


--
-- Data for Name: galery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery (publishing_id, author_id, status, description) FROM stdin;
a97d2d98-0b3e-4f29-ac98-8edfbf2b43e8	77d16713-5d52-40fb-8a30-1ccacda822f5	approved	\N
09262056-510d-42c8-a654-715f6d187856	77d16713-5d52-40fb-8a30-1ccacda822f5	approved	Ретроспектива пруда
\.


--
-- Data for Name: galery_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery_photos (path, publishing_id) FROM stdin;
b17c8412-cb10-4b85-944b-e999504de8f5.jpg	a97d2d98-0b3e-4f29-ac98-8edfbf2b43e8
a094d93e-1545-4aa3-a714-f0ecfe7de883.jpg	a97d2d98-0b3e-4f29-ac98-8edfbf2b43e8
96d82dd0-eebe-42ea-adc6-58269e5215fe.jpg	a97d2d98-0b3e-4f29-ac98-8edfbf2b43e8
9586f30a-4200-4b81-8f57-e8bf2c84cf12.jpg	a97d2d98-0b3e-4f29-ac98-8edfbf2b43e8
9660527b-abfc-4808-a2f7-d0e5780872c1.jpg	09262056-510d-42c8-a654-715f6d187856
71afa12b-df92-457a-ac63-678c62f2e380.jpg	09262056-510d-42c8-a654-715f6d187856
\.


--
-- Data for Name: partners; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners (id, name, description, trusted, status, created_at) FROM stdin;
9e3a9756-cc7e-4fd1-83ea-ba68eed3cbad	Алексей Мокеев	Алексей Мокеев - член общественной палаты администрации Владимирской области, эксперт Народного фронта | Владимир, сопредседатель благотворительного фонда "Создадим будущее вместе". Участвовал в агитации жителей города за голосование по проекту благоустройства территории пруда, так же выступал на Владимирском телевидении!	f	approved	2026-07-26 09:06:02.104498+00
28615760-e0e8-47cd-ab45-165acc4e72ad	Молодёжный клуб РГО «Владимир»	Владимирское областное отделение Русского географического общества — региональная структура одной из старейших научных организаций России, основанной в 1845 году. Отделение объединяет исследователей, педагогов, краеведов и общественных деятелей, которые занимаются изучением и сохранением природного, географического и культурно-исторического наследия Владимирского края. Среди ключевых направлений работы — экспедиционная и просветительская деятельность, экологическое воспитание, поддержка научного туризма и краеведения, а также участие в общественных инициативах по охране окружающей среды. Председателем Отделения является Антипин Сергей Владимирович.\r\nСоловьиный пруд стал одним из объектов устойчивого внимания организации: члены отделения участвовали в экологических акциях и субботниках на территории водоёма, содействовали привлечению волонтёров и широкому информированию жителей о состоянии пруда и мерах по его реабилитации. В рамках деятельности отделения формировалась экспертная позиция по вопросам сохранения городских водоёмов как элементов природного каркаса Владимира.\r\n\r\nМолодёжный клуб РГО «Владимир» создан на базе МБУ «Молодёжный центр» г. Владимира и входит в структуру Молодёжного движения Русского географического общества, объединяющего более 220 клубов по всей стране. Руководство клубом осуществляет Шишкина Светлана Александовна.\r\nМиссия клуба — приобщение молодёжи к миру «большой географии», изучение и сохранение природного и культурного наследия родного края. Активисты клуба реализуют исследовательские, просветительские и добровольческие проекты, участвуют в географических олимпиадах и конкурсах федерального уровня, организуют экспедиции и экскурсии по Владимирской области.\r\nВ работе по Соловьиному пруду Молодёжный клуб выступил важной практической силой: волонтёры клуба регулярно участвовали в субботниках и экологических акциях на территории водоёма, помогали в уборке береговой зоны, высадке растений и наведении порядка на прилегающей территории. Деятельность клуба — наглядный пример того, как молодёжь может быть не сторонним наблюдателем, а активным участником сохранения городской природы.\r\nСегодня Молодёжный клуб РГО «Владимир» продолжает развиваться: его активисты участвуют в чемпионатах России по географии, краеведческих конкурсах, лекциях-спектаклях о выдающихся исследователях Владимирского края, слётах молодёжного движения РГО и форумах добровольцев. Клуб открыт для всех, кто неравнодушен к географии, экологии и судьбе родного города.\r\n\r\nСотрудничество Владимирского отделения РГО и Молодёжного клуба «Владимир» с инициативой по сохранению Соловьиного пруда — пример того, как наука, гражданская активность и любовь к родному месту объединяются ради общего дела.	f	approved	2026-07-26 10:16:12.810786+00
9f9bf222-8082-41ed-9da9-0b47c986ded0	БПС г.Владимир. Отряд имени Андрея Дубенского 	Владимирский отряд Братства Православных Следопытов (БПС) имени Андрея Дубенского. Православные скауты (следопыты) представляют собой братство людей, стремящихся к личностному, духовному и умственному развитию.	f	approved	2026-07-26 10:25:07.15773+00
3e09d1d0-7d45-4b95-b762-709b698e8b15	Велотур клуб "ВЕЛЕС" 	Участники клуба помогают в уборке водной поверхности пруда. Помощь клуба "Велес" незаменима! Выражаем благодарность!	f	approved	2026-07-26 10:26:00.287702+00
b70b6a97-0e0e-4cd6-80d7-f00389e4815b	Институт экономики и туризма 	Студенты ИЭиТ помогают в благоустройстве территории Соловьиного пруда. Выражаем благодарность нашим помощникам!	f	approved	2026-07-26 10:26:56.750292+00
a07de85e-1f05-4efd-ab1e-9465bcdba35b	Институт архитектуры, строительства и энергетики 	Институтом архитектуры, строительства и энергетики был разработан проект по благоустройству Соловьиного пруда!	f	approved	2026-07-26 10:30:32.772225+00
d4826576-ebca-4e66-aa03-f52b649485e3	МБОУ СОШ №19	Соловьиный пруд... Такое название в своё время дали ему романтично настроенные граждане, слушавшие здесь соловьиные трели. Эти птички-невелички обитали в больших количествах в окрестных зарослях. Долгое время пруд был в запустении, заросший тиной. Сейчас его облагородили для горожан и сейчас это приятное место для прогулок.\r\nНо сколько стоило труда, чтобы появилась эта красота!!!\r\nОбучающиеся СОШ №19, их родители и классный руководитель С.В.Акимова сразу же откликнулись на призыв помочь в благоустройстве берегов водного объекта по очистке от мусора. Ребята собрали весь бытовой мусор: пакеты, пластиковые и стеклянные бутылки, фантики, жестяные банки и прочее, оставленные отдыхающими.И взрослые, и маленькие участники акции «Берег Добрых Дел» убрали 150 метров береговой линии, покрасили заборчики-ограждения.\r\nСубботники на территории Соловьиного пруда проводились неоднократно, и мы не остались в стороне. Ребята-активисты вместе со своими родителями всегда принимали участие в этой замечательной акции. А итогом данного доброго дела стали чистые берега любимого водоёма. Бережное отношение к окружающей среде — наша общая обязанность. Мы должны быть сознательными, сохранить и оставить богатое наследие нашей природы!	f	approved	2026-07-26 10:31:50.905405+00
a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8	Фотограф Ирина Виноградова	Пойманы самые искренние моменты жизни Соловьиного пруда. Эти снимки - не просто фиксация момента, а настоящая жизнь нашего пространства, рассказанная через фотографии!	f	approved	2026-07-26 10:32:54.789634+00
\.


--
-- Data for Name: partners_docs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_docs (path, partner_id) FROM stdin;
\.


--
-- Data for Name: partners_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_photos (path, partner_id) FROM stdin;
6db99004-25cd-48e5-b698-02937ee8dca3.jpg	9e3a9756-cc7e-4fd1-83ea-ba68eed3cbad
2db5d72b-b9bd-434b-bbe8-f722a78699de.jpg	9e3a9756-cc7e-4fd1-83ea-ba68eed3cbad
fe61f440-cda5-4a2a-bda9-bd2aa7f1f7d3.jpg	28615760-e0e8-47cd-ab45-165acc4e72ad
996fbfd8-9080-4263-85da-6aa2f84f3272.jpg	28615760-e0e8-47cd-ab45-165acc4e72ad
b8f95865-1bca-45ad-9ed8-af9af6023986.jpg	28615760-e0e8-47cd-ab45-165acc4e72ad
ccb0b81a-a27c-435e-af03-95444067b6be.jpg	28615760-e0e8-47cd-ab45-165acc4e72ad
51f661c9-4004-4534-bd8a-973e9576f946.jpg	9f9bf222-8082-41ed-9da9-0b47c986ded0
ca5d7117-9573-459b-a5c2-205a8c7221a3.jpg	9f9bf222-8082-41ed-9da9-0b47c986ded0
8e4116c6-b1ed-4d5e-886f-9daf201436db.jpg	9f9bf222-8082-41ed-9da9-0b47c986ded0
65059d71-102d-4a2a-b18a-5af674aaea95.jpg	9f9bf222-8082-41ed-9da9-0b47c986ded0
e3e9ed2c-2880-41e3-8828-7079330ac1a8.jpg	3e09d1d0-7d45-4b95-b762-709b698e8b15
11e56a61-44c4-4c38-83c0-baf6364a0c68.jpg	3e09d1d0-7d45-4b95-b762-709b698e8b15
eb78a677-44d9-44c9-805d-9cdd55b6f8b1.jpg	3e09d1d0-7d45-4b95-b762-709b698e8b15
27a07301-6bc0-4c28-b506-2310288bc3d9.jpg	3e09d1d0-7d45-4b95-b762-709b698e8b15
538975ab-de1e-4873-b791-8cf1a4b2ce01.jpg	b70b6a97-0e0e-4cd6-80d7-f00389e4815b
5c406cdd-289d-47cd-ac3f-5c8615ada119.jpg	b70b6a97-0e0e-4cd6-80d7-f00389e4815b
b95c8e78-6a3e-4d15-beff-d4beb09bee6e.jpg	b70b6a97-0e0e-4cd6-80d7-f00389e4815b
0a1520bf-c801-4c19-9aeb-53f3cbead815.jpg	b70b6a97-0e0e-4cd6-80d7-f00389e4815b
ca152504-4ebc-40dc-81d8-84f1a884eee9.jpg	a07de85e-1f05-4efd-ab1e-9465bcdba35b
5dd8643f-4fd3-40fe-ae10-b5da93a349d3.jpg	a07de85e-1f05-4efd-ab1e-9465bcdba35b
473605b8-2a56-4caa-8ed7-c045b8aecf5f.jpg	a07de85e-1f05-4efd-ab1e-9465bcdba35b
d266376d-c311-4713-a163-b6257243e5a7.jpg	a07de85e-1f05-4efd-ab1e-9465bcdba35b
2314f8ab-ca8e-4643-87e2-110b92ad51e3.jpg	d4826576-ebca-4e66-aa03-f52b649485e3
47ee9657-59bc-4329-9cc1-6f50e9e4503a.jpg	d4826576-ebca-4e66-aa03-f52b649485e3
0e14b129-800a-4787-92ea-ea742217492c.jpg	d4826576-ebca-4e66-aa03-f52b649485e3
de54efb1-ad1d-4d9a-a1c3-fb908e2a5bbb.jpg	d4826576-ebca-4e66-aa03-f52b649485e3
10b8fd53-708f-454d-87ea-fcb29e91e56b.jpg	a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8
963b1cb6-899d-47fe-87d1-4367afd5b828.jpg	a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8
34550bdd-2024-401f-97dd-035bd43c75bf.jpg	a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8
6db98e0a-ff60-4c80-80fe-eb04ff5a6148.jpg	a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8
\.


--
-- Data for Name: partners_reps; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_reps (partner_id, user_id) FROM stdin;
9e3a9756-cc7e-4fd1-83ea-ba68eed3cbad	77d16713-5d52-40fb-8a30-1ccacda822f5
28615760-e0e8-47cd-ab45-165acc4e72ad	77d16713-5d52-40fb-8a30-1ccacda822f5
9f9bf222-8082-41ed-9da9-0b47c986ded0	77d16713-5d52-40fb-8a30-1ccacda822f5
3e09d1d0-7d45-4b95-b762-709b698e8b15	77d16713-5d52-40fb-8a30-1ccacda822f5
b70b6a97-0e0e-4cd6-80d7-f00389e4815b	77d16713-5d52-40fb-8a30-1ccacda822f5
a07de85e-1f05-4efd-ab1e-9465bcdba35b	77d16713-5d52-40fb-8a30-1ccacda822f5
d4826576-ebca-4e66-aa03-f52b649485e3	77d16713-5d52-40fb-8a30-1ccacda822f5
a92ef60a-d1cf-4b3b-97fa-cb35ac6a64b8	77d16713-5d52-40fb-8a30-1ccacda822f5
\.


--
-- Data for Name: partners_socials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_socials (partner_id, social, url) FROM stdin;
9e3a9756-cc7e-4fd1-83ea-ba68eed3cbad	Other	https://vladtv.ru/society/153782/
28615760-e0e8-47cd-ab45-165acc4e72ad	VK	https://vk.com/rgo33
9f9bf222-8082-41ed-9da9-0b47c986ded0	VK	https://vk.ru/bps.vladimir33
3e09d1d0-7d45-4b95-b762-709b698e8b15	VK	https://vk.com/veles33
b70b6a97-0e0e-4cd6-80d7-f00389e4815b	VK	https://vk.com/instituteeit
\.


--
-- Data for Name: stories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories (id, author_id, title, content, status, created_at, updated_at, updated_by) FROM stdin;
2	77d16713-5d52-40fb-8a30-1ccacda822f5	Народное спасение и масштабное возрождение	Долгое время Соловьиный пруд находился в запустении, зарастал тиной и постепенно превращался в свалку бытового мусора посреди жилой застройки. Экологическая история пруда — это хроника борьбы жителей за жизнь уникальной городской экосистемы.\nНародные субботники: В 2014–2015 годах инициативная группа горожан и активистов ВлГУ забила тревогу. Они своими силами провели масштабные субботники, добились очистки дна от ила, убрали хлам и вернули пруду способность наполняться родниковой водой. На воду спустили плавающий домик для уток, а в воду запустили карасей и мальков. Пруд стал настоящим оазисом, однако маленькая замкнутая экосистема регулярно подвергалась угрозам: от нехватки кислорода зимой до сообщений о незаконных сливах.\nНовый этап (2026 год): \nЛетом 2026 года началась масштабная экологическая регенерация водоема по программе комфортной городской среды. Пруд полностью осушили, чтобы бережно выловить рыбу, вычистить дно от многолетних донных отложений и мусора. Самым важным шагом стало решение пробурить артезианскую скважину глубиной 180 метров. Она будет постоянно питать Соловьиный пруд чистой водой, защищая его от высыхания и зацветания, что позволит полностью сохранить хрупкий биоценоз.	approved	2026-07-26 08:40:44.717077+00	2026-07-26 08:40:44.717077+00	\N
3	77d16713-5d52-40fb-8a30-1ccacda822f5	От глиняного карьера до романтичных трелей	История самого старого из сохранившихся городских водоемов Владимира началась в XIX веке. В те времена на пустыре за Юрьевской заставой (ныне район Новой слободы) активно работали частные кирпичные заводы Студьицкого и Ермолаева, позже объединенные в завод имени Володарского. \n\nРождение водоема: Рабочие годами выкапывали из огромного карьера глину для производства кирпичей. Со временем производство закрылось, а глубокий котлован глубиной более 4,5 метров стал стремительно заполняться чистейшей водой из подземных природных ключей.\n\nОткуда пошли названия: Местные жители долгое время называли водоем «Кирпичики» — в память о заводе. Однако народное и самое известное название — «Соловьиный» — пруд получил благодаря густым зеленым зарослям вокруг, в которых каждую весну собирались сотни птиц, оглашая округу звонкими трелями. Водоем более полувека использовался для технического водоснабжения, но постепенно превратился в любимое место отдыха горожан.	approved	2026-07-26 08:43:10.331352+00	2026-07-26 08:43:10.331352+00	\N
4	77d16713-5d52-40fb-8a30-1ccacda822f5	Как преобразили Соловьиный пруд	Отвечает Алексей МИГАЧЁВ, директор департамента природопользования и охраны окружающей среды администрации Владимирской области: - Жители окрестных домов на улице Студенческой несколько лет боролись за сохранение Соловьиного пруда. Теперь водоём преобразился: его очистили от мусора, тины и грязи, а дно углубили на 1,5 метра, теперь его глубина - около 3 метров. Для возрождения популяции рыб закупили и выпустили 5 октября в водоём 25 кг молодого карася. Рыба должна помочь восстановить экосистему пруда после работ по его очистке и углублению. Кстати, на берегу должны установить таблички, запрещающие ловить рыбу. В планах - благоустройство примыкающей территории: вокруг водоёма появятся освещённые асфальтированные дорожки, а берега обсадят деревьями. Сейчас активисты хотят, чтобы Соловьиный пруд признали особо охраняемой природной территорией. \n(Источник: https://news.rambler.ru/ecology/31623229-kak-preobrazili-solovinyy-prud-vo-vladimire/)	approved	2026-07-26 10:39:00.341293+00	2026-07-26 10:39:00.341293+00	\N
\.


--
-- Data for Name: stories_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_images (story_id, path) FROM stdin;
2	78b661ec-ee72-4f07-b6f4-e530c1368df0.jpg
2	c7e0273e-eb03-46c3-9e93-80c3f7eb36dc.jpg
3	199c85a3-5617-4261-a9a4-53d3ecef28ff.jpg
\.


--
-- Data for Name: stories_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_tags (story_id, tag_id) FROM stdin;
2	2
3	1
4	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, name, surname, avatar, role) FROM stdin;
77d16713-5d52-40fb-8a30-1ccacda822f5	admin@admin.ru	8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918	Администратор	Сайта	admin_avatar.png	admin
\.


--
-- Name: available_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.available_tags_id_seq', 3, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_id_seq', 2, true);


--
-- Name: stories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stories_id_seq', 4, true);


--
-- Name: available_tags available_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.available_tags
    ADD CONSTRAINT available_tags_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: galery_photos galery_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_pkey PRIMARY KEY (path);


--
-- Name: galery galery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_pkey PRIMARY KEY (publishing_id);


--
-- Name: partners_docs partners_docs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_docs
    ADD CONSTRAINT partners_docs_pkey PRIMARY KEY (path);


--
-- Name: partners partners_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_name_key UNIQUE (name);


--
-- Name: partners_photos partners_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_pkey PRIMARY KEY (path);


--
-- Name: partners partners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_pkey PRIMARY KEY (id);


--
-- Name: stories stories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: events events_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: events_images events_images_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_images
    ADD CONSTRAINT events_images_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: galery galery_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: galery_photos galery_photos_publishing_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_publishing_id_fkey FOREIGN KEY (publishing_id) REFERENCES public.galery(publishing_id);


--
-- Name: partners_docs partners_docs_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_docs
    ADD CONSTRAINT partners_docs_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_photos partners_photos_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_reps partners_reps_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_reps
    ADD CONSTRAINT partners_reps_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_reps partners_reps_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_reps
    ADD CONSTRAINT partners_reps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: partners_socials partners_socials_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_socials
    ADD CONSTRAINT partners_socials_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: stories stories_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: stories_images stories_images_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_images
    ADD CONSTRAINT stories_images_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.available_tags(id);


--
-- Name: stories stories_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict GH1eW69dBG9hgFOrIjnRJRM9rREBejHKeDHWM0SOhaYO0CYEBXezvn1WabK4eaX

