--
-- PostgreSQL database dump
--

\restrict zLji4OXN9B5VC4zW2BKH7kcQCInD0ZQkRw3UUjyW02GhiwZsCefpbFfmwTrTvHG

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: galery_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.galery_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.galery_status OWNER TO postgres;

--
-- Name: partner_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.partner_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.partner_status OWNER TO postgres;

--
-- Name: story_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.story_status AS ENUM (
    'new',
    'approved',
    'rejected'
);


ALTER TYPE public.story_status OWNER TO postgres;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'user'
);


ALTER TYPE public.user_role OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: available_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.available_tags (
    id integer NOT NULL,
    name character varying(64)
);


ALTER TABLE public.available_tags OWNER TO postgres;

--
-- Name: available_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.available_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.available_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    name character varying(64),
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    date timestamp with time zone NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_images (
    event_id integer,
    path character varying(255),
    base_code text
);


ALTER TABLE public.events_images OWNER TO postgres;

--
-- Name: galery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery (
    publishing_id character varying(255) NOT NULL,
    author_id uuid,
    status public.galery_status NOT NULL,
    description character varying(1023)
);


ALTER TABLE public.galery OWNER TO postgres;

--
-- Name: galery_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galery_photos (
    path character varying(255) NOT NULL,
    publishing_id character varying(255)
);


ALTER TABLE public.galery_photos OWNER TO postgres;

--
-- Name: partners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    trusted boolean DEFAULT false,
    status public.partner_status NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.partners OWNER TO postgres;

--
-- Name: partners_docs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_docs (
    path character varying NOT NULL,
    partner_id uuid
);


ALTER TABLE public.partners_docs OWNER TO postgres;

--
-- Name: partners_photos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_photos (
    path character varying(255) NOT NULL,
    partner_id uuid,
    base_code text
);


ALTER TABLE public.partners_photos OWNER TO postgres;

--
-- Name: partners_reps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_reps (
    partner_id uuid,
    user_id uuid
);


ALTER TABLE public.partners_reps OWNER TO postgres;

--
-- Name: partners_socials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners_socials (
    partner_id uuid,
    social character varying(64) NOT NULL,
    url character varying(255) NOT NULL
);


ALTER TABLE public.partners_socials OWNER TO postgres;

--
-- Name: stories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories (
    id integer NOT NULL,
    author_id uuid,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    status public.story_status NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    updated_by uuid
);


ALTER TABLE public.stories OWNER TO postgres;

--
-- Name: stories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_images (
    story_id integer,
    path character varying(255),
    base_code text
);


ALTER TABLE public.stories_images OWNER TO postgres;

--
-- Name: stories_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stories_tags (
    story_id integer,
    tag_id integer
);


ALTER TABLE public.stories_tags OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255),
    name character varying(32) NOT NULL,
    role public.user_role NOT NULL,
    verified boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: verification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification (
    email character varying(255),
    code character varying(16),
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.verification OWNER TO postgres;

--
-- Data for Name: available_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.available_tags (id, name) FROM stdin;
1	Реставрация
2	История пруда
3	Экология
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (id, name, description, created_at, updated_at, created_by, date) FROM stdin;
1	Тайны старого карьера: от кирпича до оазиса	Исторический пикник-лекторий под открытым небом. Краеведы расскажут историю Новой слободы и кирпичного завода XIX века, покажут архивные фотографии пруда «Кирпичики», а активисты поделятся хрониками борьбы за спасение водоема. Завершится вечер акустическим концертом у воды.	2026-07-29 09:20:33.874474+00	2026-07-29 09:20:33.874474+00	c3dde2b6-6cc4-446e-bdaf-561f45d18548	2027-07-21 12:00:00+00
2	Птичий перезвон на Соловьином	Эко-фестиваль в честь возвращения птиц на обновленный водоем. В программе: мастер-класс от орнитологов по распознаванию птичьих голосов, развешивание правильных кормушек, лекция о бережном отношении к уткам и запуск первой партии рыбы в очищенный пруд.	2026-07-29 09:21:05.671425+00	2026-07-29 09:21:05.671425+00	c3dde2b6-6cc4-446e-bdaf-561f45d18548	2026-05-16 11:00:00+00
\.


--
-- Data for Name: events_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events_images (event_id, path, base_code) FROM stdin;
\.


--
-- Data for Name: galery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery (publishing_id, author_id, status, description) FROM stdin;
74e2218d-9d47-4120-abbe-57b65e884089	c3dde2b6-6cc4-446e-bdaf-561f45d18548	approved	Ретроспектива пруда
5e05b5df-628c-4f54-8f0f-4e947a0e1744	c3dde2b6-6cc4-446e-bdaf-561f45d18548	approved	\N
\.


--
-- Data for Name: galery_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.galery_photos (path, publishing_id) FROM stdin;
8b328b86-77f2-4f99-ad87-931494b27a74.jpg	74e2218d-9d47-4120-abbe-57b65e884089
d0730d30-98d7-43b9-b764-c1c61183bdbe.jpg	74e2218d-9d47-4120-abbe-57b65e884089
e02cba2e-448b-48bc-93db-0cdc50e0e77f.jpg	5e05b5df-628c-4f54-8f0f-4e947a0e1744
60c70c5e-2293-4569-a4f6-5b3075bc2f4d.jpg	5e05b5df-628c-4f54-8f0f-4e947a0e1744
51b475a3-74c3-4b4d-b3a6-a3b7f6fb0ccd.jpg	5e05b5df-628c-4f54-8f0f-4e947a0e1744
ba2afb7d-5c93-4e4a-9a29-26ba4df6b354.jpg	5e05b5df-628c-4f54-8f0f-4e947a0e1744
\.


--
-- Data for Name: partners; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners (id, name, description, trusted, status, created_at) FROM stdin;
071ce421-f272-48ed-bc75-48c10c3eb45a	Алексей Мокеев	Алексей Мокеев - член общественной палаты администрации Владимирской области, эксперт Народного фронта | Владимир, сопредседатель благотворительного фонда "Создадим будущее вместе". Участвовал в агитации жителей города за голосование по проекту благоустройства территории пруда, так же выступал на Владимирском телевидении!	f	approved	2026-07-29 09:21:58.498554+00
9322db67-8401-4aed-9d0e-455078534724	Молодёжный клуб РГО «Владимир»	Владимирское областное отделение Русского географического общества — региональная структура одной из старейших научных организаций России, основанной в 1845 году. Отделение объединяет исследователей, педагогов, краеведов и общественных деятелей, которые занимаются изучением и сохранением природного, географического и культурно-исторического наследия Владимирского края. Среди ключевых направлений работы — экспедиционная и просветительская деятельность, экологическое воспитание, поддержка научного туризма и краеведения, а также участие в общественных инициативах по охране окружающей среды. Председателем Отделения является Антипин Сергей Владимирович.\r\nСоловьиный пруд стал одним из объектов устойчивого внимания организации: члены отделения участвовали в экологических акциях и субботниках на территории водоёма, содействовали привлечению волонтёров и широкому информированию жителей о состоянии пруда и мерах по его реабилитации. В рамках деятельности отделения формировалась экспертная позиция по вопросам сохранения городских водоёмов как элементов природного каркаса Владимира.\r\n\r\nМолодёжный клуб РГО «Владимир» создан на базе МБУ «Молодёжный центр» г. Владимира и входит в структуру Молодёжного движения Русского географического общества, объединяющего более 220 клубов по всей стране. Руководство клубом осуществляет Шишкина Светлана Александовна.\r\nМиссия клуба — приобщение молодёжи к миру «большой географии», изучение и сохранение природного и культурного наследия родного края. Активисты клуба реализуют исследовательские, просветительские и добровольческие проекты, участвуют в географических олимпиадах и конкурсах федерального уровня, организуют экспедиции и экскурсии по Владимирской области.\r\nВ работе по Соловьиному пруду Молодёжный клуб выступил важной практической силой: волонтёры клуба регулярно участвовали в субботниках и экологических акциях на территории водоёма, помогали в уборке береговой зоны, высадке растений и наведении порядка на прилегающей территории. Деятельность клуба — наглядный пример того, как молодёжь может быть не сторонним наблюдателем, а активным участником сохранения городской природы.\r\nСегодня Молодёжный клуб РГО «Владимир» продолжает развиваться: его активисты участвуют в чемпионатах России по географии, краеведческих конкурсах, лекциях-спектаклях о выдающихся исследователях Владимирского края, слётах молодёжного движения РГО и форумах добровольцев. Клуб открыт для всех, кто неравнодушен к географии, экологии и судьбе родного города.\r\n\r\nСотрудничество Владимирского отделения РГО и Молодёжного клуба «Владимир» с инициативой по сохранению Соловьиного пруда — пример того, как наука, гражданская активность и любовь к родному месту объединяются ради общего дела.	f	approved	2026-07-29 09:22:31.074786+00
9e9b03bf-5d73-4657-88a9-9677e8a4cf68	БПС г.Владимир. Отряд имени Андрея Дубенского	Владимирский отряд Братства Православных Следопытов (БПС) имени Андрея Дубенского. Православные скауты (следопыты) представляют собой братство людей, стремящихся к личностному, духовному и умственному развитию.	f	approved	2026-07-29 09:23:16.351878+00
e1d27acb-9c91-473a-a239-ddb1937705d8	Велотур клуб "ВЕЛЕС" 	Участники клуба помогают в уборке водной поверхности пруда. Помощь клуба "Велес" незаменима! Выражаем благодарность!	t	approved	2026-07-29 09:23:50.214791+00
5eef428b-374a-4456-95f0-b46a8a9b5ceb	Институт экономики и туризма 	Студенты ИЭиТ помогают в благоустройстве территории Соловьиного пруда. Выражаем благодарность нашим помощникам!	f	approved	2026-07-29 09:24:51.704947+00
196d6b7d-bb47-4f23-931b-da4b4e4a0768	Институт архитектуры, строительства и энергетики	Институтом архитектуры, строительства и энергетики был разработан проект по благоустройству Соловьиного пруда!	f	approved	2026-07-29 09:27:40.565027+00
7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	МБОУ СОШ №19	Соловьиный пруд... Такое название в своё время дали ему романтично настроенные граждане, слушавшие здесь соловьиные трели. Эти птички-невелички обитали в больших количествах в окрестных зарослях. Долгое время пруд был в запустении, заросший тиной. Сейчас его облагородили для горожан и сейчас это приятное место для прогулок.\r\nНо сколько стоило труда, чтобы появилась эта красота!!!\r\nОбучающиеся СОШ №19, их родители и классный руководитель С.В.Акимова сразу же откликнулись на призыв помочь в благоустройстве берегов водного объекта по очистке от мусора. Ребята собрали весь бытовой мусор: пакеты, пластиковые и стеклянные бутылки, фантики, жестяные банки и прочее, оставленные отдыхающими.И взрослые, и маленькие участники акции «Берег Добрых Дел» убрали 150 метров береговой линии, покрасили заборчики-ограждения.\r\nСубботники на территории Соловьиного пруда проводились неоднократно, и мы не остались в стороне. Ребята-активисты вместе со своими родителями всегда принимали участие в этой замечательной акции. А итогом данного доброго дела стали чистые берега любимого водоёма. Бережное отношение к окружающей среде — наша общая обязанность. Мы должны быть сознательными, сохранить и оставить богатое наследие нашей природы!	f	approved	2026-07-29 09:28:09.510961+00
6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	Фотограф Ирина Виноградова	Пойманы самые искренние моменты жизни Соловьиного пруда. Эти снимки - не просто фиксация момента, а настоящая жизнь нашего пространства, рассказанная через фотографии!	f	approved	2026-07-29 09:28:32.987267+00
\.


--
-- Data for Name: partners_docs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_docs (path, partner_id) FROM stdin;
0577cde7-2a42-4259-b463-f485e30dadb0.pdf	e1d27acb-9c91-473a-a239-ddb1937705d8
\.


--
-- Data for Name: partners_photos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_photos (path, partner_id, base_code) FROM stdin;
148bb8c3-e367-4301-9077-e6e2787b4709.webp	071ce421-f272-48ed-bc75-48c10c3eb45a	\N
a9b28929-7be8-4492-9c83-4eea2a20e431.webp	071ce421-f272-48ed-bc75-48c10c3eb45a	\N
57481573-0ce1-4002-882d-d65adf601c53.webp	9322db67-8401-4aed-9d0e-455078534724	\N
37742aa2-1d21-49ec-aa69-a8ab62024051.webp	9322db67-8401-4aed-9d0e-455078534724	\N
23801749-577a-4e5d-9ba4-49e022220522.webp	9322db67-8401-4aed-9d0e-455078534724	\N
c6114862-e534-40b6-847e-1b356e22de0e.webp	9322db67-8401-4aed-9d0e-455078534724	\N
3db61ac9-a2fe-4440-9f29-0210f0417b2d.webp	9e9b03bf-5d73-4657-88a9-9677e8a4cf68	\N
90ac3069-1ecd-4ec8-b125-5991f82394fb.webp	9e9b03bf-5d73-4657-88a9-9677e8a4cf68	\N
b9a0251f-91c8-4894-b69d-10ed5e697f6a.webp	9e9b03bf-5d73-4657-88a9-9677e8a4cf68	\N
30becfe8-f8f0-45f8-84a7-0b52254e70de.webp	9e9b03bf-5d73-4657-88a9-9677e8a4cf68	\N
7afd723b-c891-4c5c-808a-666812729d13.webp	e1d27acb-9c91-473a-a239-ddb1937705d8	\N
32c0d012-f07a-439b-8acd-8db05dd3a8a0.webp	e1d27acb-9c91-473a-a239-ddb1937705d8	\N
3ca91fc3-d450-4520-bfc1-18309a69be2d.webp	e1d27acb-9c91-473a-a239-ddb1937705d8	\N
9e416f97-7fc4-417a-a06e-5e52302288c5.webp	e1d27acb-9c91-473a-a239-ddb1937705d8	\N
74d174b3-4ffb-4057-935e-6bce4cd524f0.webp	5eef428b-374a-4456-95f0-b46a8a9b5ceb	\N
41a41f97-c686-4d94-8f18-256af0cf56c3.webp	5eef428b-374a-4456-95f0-b46a8a9b5ceb	\N
e210c6a6-db33-4cd3-9cb4-094b1eeb7466.webp	5eef428b-374a-4456-95f0-b46a8a9b5ceb	\N
7ba2d91c-f959-44f1-9d35-29e94823be95.webp	5eef428b-374a-4456-95f0-b46a8a9b5ceb	\N
6a9efdde-7d7c-4e15-8ffd-0b5688c8d7ec.webp	196d6b7d-bb47-4f23-931b-da4b4e4a0768	\N
4a426be2-b45e-4f0a-a87c-23c3e879dc35.webp	196d6b7d-bb47-4f23-931b-da4b4e4a0768	\N
3af75da6-b052-4989-abdc-7456d8e613c4.webp	196d6b7d-bb47-4f23-931b-da4b4e4a0768	\N
be94ffca-3c69-4045-ac8f-0d07e158ce59.webp	196d6b7d-bb47-4f23-931b-da4b4e4a0768	\N
74838f05-cdc5-4cd7-8eb0-f0962507a2fe.webp	7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	\N
308212aa-e82c-4c85-ad1c-716790bc61a8.webp	7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	\N
01fcf23d-79d9-4602-8a51-9fa6bdf2bf40.webp	7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	\N
b0f9c21e-f43c-4217-bacf-4619951e7665.webp	7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	\N
68eed1ae-6df7-4075-a9dc-e51c4f3b4f25.webp	6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	\N
819c275c-8198-4700-9fbc-279c383a2092.webp	6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	\N
114dcb2c-4aea-4c79-a47f-e0eb4c50206e.webp	6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	\N
097c7f53-1982-44b2-b5f2-4d8286a67a80.webp	6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	\N
\.


--
-- Data for Name: partners_reps; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_reps (partner_id, user_id) FROM stdin;
071ce421-f272-48ed-bc75-48c10c3eb45a	c3dde2b6-6cc4-446e-bdaf-561f45d18548
9322db67-8401-4aed-9d0e-455078534724	c3dde2b6-6cc4-446e-bdaf-561f45d18548
9e9b03bf-5d73-4657-88a9-9677e8a4cf68	c3dde2b6-6cc4-446e-bdaf-561f45d18548
e1d27acb-9c91-473a-a239-ddb1937705d8	c3dde2b6-6cc4-446e-bdaf-561f45d18548
5eef428b-374a-4456-95f0-b46a8a9b5ceb	c3dde2b6-6cc4-446e-bdaf-561f45d18548
196d6b7d-bb47-4f23-931b-da4b4e4a0768	c3dde2b6-6cc4-446e-bdaf-561f45d18548
7bbaba41-40b5-4c65-bfb2-3e4fc10a41fe	c3dde2b6-6cc4-446e-bdaf-561f45d18548
6e1d426b-a9b4-4387-b9d4-6b9b3cf6df5f	c3dde2b6-6cc4-446e-bdaf-561f45d18548
\.


--
-- Data for Name: partners_socials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partners_socials (partner_id, social, url) FROM stdin;
071ce421-f272-48ed-bc75-48c10c3eb45a	Other	https://vladtv.ru/society/153782/
9322db67-8401-4aed-9d0e-455078534724	VK	https://vk.ru/rgo33
9e9b03bf-5d73-4657-88a9-9677e8a4cf68	VK	https://vk.ru/bps.vladimir33
e1d27acb-9c91-473a-a239-ddb1937705d8	VK	https://vk.com/veles33
5eef428b-374a-4456-95f0-b46a8a9b5ceb	VK	https://vk.ru/instituteeit
\.


--
-- Data for Name: stories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories (id, author_id, title, content, status, created_at, updated_at, updated_by) FROM stdin;
1	c3dde2b6-6cc4-446e-bdaf-561f45d18548	Как преобразили Соловьиный пруд	Отвечает Алексей МИГАЧЁВ, директор департамента природопользования и охраны окружающей среды администрации Владимирской области: - Жители окрестных домов на улице Студенческой несколько лет боролись за сохранение Соловьиного пруда. Теперь водоём преобразился: его очистили от мусора, тины и грязи, а дно углубили на 1,5 метра, теперь его глубина - около 3 метров. Для возрождения популяции рыб закупили и выпустили 5 октября в водоём 25 кг молодого карася. Рыба должна помочь восстановить экосистему пруда после работ по его очистке и углублению. Кстати, на берегу должны установить таблички, запрещающие ловить рыбу. В планах - благоустройство примыкающей территории: вокруг водоёма появятся освещённые асфальтированные дорожки, а берега обсадят деревьями. Сейчас активисты хотят, чтобы Соловьиный пруд признали особо охраняемой природной территорией. \n(Источник: https://news.rambler.ru/ecology/31623229-kak-preobrazili-solovinyy-prud-vo-vladimire/)	approved	2026-07-29 09:18:53.630252+00	2026-07-29 09:18:53.630252+00	\N
2	c3dde2b6-6cc4-446e-bdaf-561f45d18548	От глиняного карьера до романтичных трелей	История самого старого из сохранившихся городских водоемов Владимира началась в XIX веке. В те времена на пустыре за Юрьевской заставой (ныне район Новой слободы) активно работали частные кирпичные заводы Студьицкого и Ермолаева, позже объединенные в завод имени Володарского. \n\nРождение водоема: Рабочие годами выкапывали из огромного карьера глину для производства кирпичей. Со временем производство закрылось, а глубокий котлован глубиной более 4,5 метров стал стремительно заполняться чистейшей водой из подземных природных ключей.\n\nОткуда пошли названия: Местные жители долгое время называли водоем «Кирпичики» — в память о заводе. Однако народное и самое известное название — «Соловьиный» — пруд получил благодаря густым зеленым зарослям вокруг, в которых каждую весну собирались сотни птиц, оглашая округу звонкими трелями. Водоем более полувека использовался для технического водоснабжения, но постепенно превратился в любимое место отдыха горожан.	approved	2026-07-29 09:19:18.203769+00	2026-07-29 09:19:18.203769+00	\N
3	c3dde2b6-6cc4-446e-bdaf-561f45d18548	Народное спасение и масштабное возрождение	Долгое время Соловьиный пруд находился в запустении, зарастал тиной и постепенно превращался в свалку бытового мусора посреди жилой застройки. Экологическая история пруда — это хроника борьбы жителей за жизнь уникальной городской экосистемы.\nНародные субботники: В 2014–2015 годах инициативная группа горожан и активистов ВлГУ забила тревогу. Они своими силами провели масштабные субботники, добились очистки дна от ила, убрали хлам и вернули пруду способность наполняться родниковой водой. На воду спустили плавающий домик для уток, а в воду запустили карасей и мальков. Пруд стал настоящим оазисом, однако маленькая замкнутая экосистема регулярно подвергалась угрозам: от нехватки кислорода зимой до сообщений о незаконных сливах.\nНовый этап (2026 год): \nЛетом 2026 года началась масштабная экологическая регенерация водоема по программе комфортной городской среды. Пруд полностью осушили, чтобы бережно выловить рыбу, вычистить дно от многолетних донных отложений и мусора. Самым важным шагом стало решение пробурить артезианскую скважину глубиной 180 метров. Она будет постоянно питать Соловьиный пруд чистой водой, защищая его от высыхания и зацветания, что позволит полностью сохранить хрупкий биоценоз.	approved	2026-07-29 09:19:54.190787+00	2026-07-29 09:19:54.190787+00	\N
\.


--
-- Data for Name: stories_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_images (story_id, path, base_code) FROM stdin;
2	330f3e0a-ab1b-40d2-804b-746c3c0d4de5.webp	\N
3	32e05396-1c3e-4055-9be0-5f537bcac5f3.webp	\N
3	a7c79d31-703d-4c4d-9bf0-d7293e0faa51.webp	\N
\.


--
-- Data for Name: stories_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stories_tags (story_id, tag_id) FROM stdin;
1	1
2	2
3	3
3	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, name, role, verified) FROM stdin;
c3dde2b6-6cc4-446e-bdaf-561f45d18548	admin@admin.ru	Администратор Сайта	admin	\N
\.


--
-- Data for Name: verification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verification (email, code, created_at) FROM stdin;
\.


--
-- Name: available_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.available_tags_id_seq', 3, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_id_seq', 2, true);


--
-- Name: stories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stories_id_seq', 3, true);


--
-- Name: available_tags available_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.available_tags
    ADD CONSTRAINT available_tags_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: galery_photos galery_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_pkey PRIMARY KEY (path);


--
-- Name: galery galery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_pkey PRIMARY KEY (publishing_id);


--
-- Name: partners_docs partners_docs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_docs
    ADD CONSTRAINT partners_docs_pkey PRIMARY KEY (path);


--
-- Name: partners partners_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_name_key UNIQUE (name);


--
-- Name: partners_photos partners_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_pkey PRIMARY KEY (path);


--
-- Name: partners partners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_pkey PRIMARY KEY (id);


--
-- Name: stories stories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: events events_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: events_images events_images_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_images
    ADD CONSTRAINT events_images_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: galery galery_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery
    ADD CONSTRAINT galery_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: galery_photos galery_photos_publishing_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galery_photos
    ADD CONSTRAINT galery_photos_publishing_id_fkey FOREIGN KEY (publishing_id) REFERENCES public.galery(publishing_id);


--
-- Name: partners_docs partners_docs_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_docs
    ADD CONSTRAINT partners_docs_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_photos partners_photos_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_photos
    ADD CONSTRAINT partners_photos_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_reps partners_reps_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_reps
    ADD CONSTRAINT partners_reps_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: partners_reps partners_reps_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_reps
    ADD CONSTRAINT partners_reps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: partners_socials partners_socials_partner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners_socials
    ADD CONSTRAINT partners_socials_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id);


--
-- Name: stories stories_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: stories_images stories_images_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_images
    ADD CONSTRAINT stories_images_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_story_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id) ON DELETE CASCADE;


--
-- Name: stories_tags stories_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories_tags
    ADD CONSTRAINT stories_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.available_tags(id);


--
-- Name: stories stories_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stories
    ADD CONSTRAINT stories_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: verification verification_email_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_email_fkey FOREIGN KEY (email) REFERENCES public.users(email);


--
-- PostgreSQL database dump complete
--

\unrestrict zLji4OXN9B5VC4zW2BKH7kcQCInD0ZQkRw3UUjyW02GhiwZsCefpbFfmwTrTvHG

