CREATE TYPE user_role AS ENUM ('admin', 'user');
CREATE TYPE story_status AS ENUM ('new', 'approved', 'rejected');

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(32) NOT NULL,
    surname VARCHAR(32) NOT NULL,
    avatar VARCHAR(255),
    role user_role NOT NULL
);

CREATE TABLE stories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status story_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_by UUID REFERENCES users(id)
);

CREATE TABLE available_tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64)
);

CREATE TABLE stories_tags (
    story_id INT REFERENCES stories(id),
    tag_id INT REFERENCES available_tags(id)
);

CREATE TABLE stories_images (
    story_id INT REFERENCES stories(id),
    path VARCHAR(255)
);

CREATE TABLE events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    date TIMESTAMPTZ NOT NULL
);