CREATE TYPE user_role AS ENUM ('admin', 'user');
CREATE TYPE story_status AS ENUM ('new', 'approved', 'rejected');
CREATE TYPE galery_status AS ENUM ('new', 'approved', 'rejected');
CREATE TYPE partner_status AS ENUM ('new', 'approved', 'rejected');

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(32) NOT NULL,
    surname VARCHAR(32) NOT NULL,
    avatar VARCHAR(255),
    role user_role NOT NULL
);

-- Истории
CREATE TABLE IF NOT EXISTS stories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status story_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_by UUID REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS available_tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS stories_tags (
    story_id INT REFERENCES stories(id) ON DELETE CASCADE,
    tag_id INT REFERENCES available_tags(id)
);

CREATE TABLE IF NOT EXISTS stories_images (
    story_id INT REFERENCES stories(id) ON DELETE CASCADE,
    path VARCHAR(255)
);

-- События
CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    date TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS events_images (
    event_id INT REFERENCES events(id),
    path VARCHAR(255)
);

-- Фотогалерея
CREATE TABLE IF NOT EXISTS galery (
    publishing_id VARCHAR(255) PRIMARY KEY,
    author_id UUID REFERENCES users(id),
    status galery_status NOT NULL
);

CREATE TABLE IF NOT EXISTS galery_photos (
    path VARCHAR(255) PRIMARY KEY,
    publishing_id VARCHAR(255) REFERENCES galery(publishing_id)
);

-- Партнёры
CREATE TABLE IF NOT EXISTS partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    trusted BOOLEAN DEFAULT FALSE,  
    status partner_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS partners_photos (
    path VARCHAR(255) PRIMARY KEY,
    partner_id UUID REFERENCES partners(id)
);

CREATE TABLE IF NOT EXISTS partners_docs (
    path VARCHAR PRIMARY KEY,
    partner_id UUID REFERENCES partners(id)
);

-- Представители партнёров
CREATE TABLE IF NOT EXISTS partners_reps (
    partner_id UUID REFERENCES partners(id),
    user_id UUID REFERENCES users(id)
);

-- Соц сети партнёров
CREATE TABLE IF NOT EXISTS partners_socials (
    partner_id UUID REFERENCES partners(id),
    social VARCHAR(64) NOT NULL,
    url VARCHAR(255) NOT NULL
);